name: Merge PR

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed
    branches:
      - changeset-release/main
      - chore/changeset-lockfile-update

jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Create Github App Token
        if: ${{ github.actor == 'poc-packages-monorepo-app-token[bot]' }}
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Auto-merge PR
        if: ${{ github.actor == 'poc-packages-monorepo-app-token[bot]' }}
        run: gh pr merge --admin --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
