name: Merge PR

on:
  workflow_call:
    inputs:
      app-id:
        required: true
        type: string
    secrets:
      private_key:
        required: true

jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Create Github App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ inputs.app-id }}
          private-key: ${{ secrets.private_key }}
      - name: Auto-merge PR
        run: gh pr merge --admin --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
